#!/bin/bash

#####################################################################
#
#                   Easy Nvidia Driver Installer
#
#               Jaime Roque | https://github.com/jjrbfi 
#
# source: 
#   - https://docs.nvidia.com/cuda/cuda-installation-guide-linux
#   - https://docs.nvidia.com/deeplearning/tensorrt/install-guide
#####################################################################


nvidia_driver(){
    echo "Updating repository and installing drivers"
    sudo apt update
    sudo mkdir /usr/lib/nvidia
    sudo apt install nvidia-driver-460

    echo -e "\n\nDriver installed. You should reboot your computer."
}


cuda_driver(){
    echo "Installing Cuda"

    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
    sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
    sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
    sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
    sudo apt update
    sudo apt -y install cuda
    echo -e "# NVIDIA CUDA Toolkit\n
    export PATH=/usr/local/cuda-11.2/bin:$PATH\n
    export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64\n
    export CPATH=/usr/local/cuda-11.2/targets/x86_64-linux/include:$CPATH" >> ~/.bashrc
    source .bashrc

    echo -e "\n\nDriver installed. You should reboot your computer."
}



cudnn_driver(){

    echo "Installing CUDNN"

    sudo apt update
    sudo apt install libcudnn8 libcudnn8-dev
    echo -e "\n\nDriver installed. You should reboot your computer."

}


while getopts "ih" OPTION
do
	case $OPTION in
		i)
            if [ -z $2 ]; then
                echo "Expected something after flag -i"
            elif [ $2 == "nvidia" ]; then
                nvidia_driver 
            elif [ $2 == "cuda" ]; then
                cuda_driver 
            elif [ $2 == "cudnn" ]; then
                cudnn_driver   
            else
			    echo "Error. Please check the info with -h"
            exit
            fi
			;;
		h)
            echo -e "Installation methods:\n\n./endi -i nvidia [Nvidia drivers]\n./endi -i cuda   [Cuda drivers]\n./endi -i cudnn  [CUDNN drivers]"
			exit
			;;

		\?)
            echo -e "Installation methods:\n\n./endi -i nvidia [Nvidia drivers]\n./endi -i cuda   [Cuda drivers]\n./endi -i cudnn  [CUDNN drivers]"

			exit
			;;
	esac
done

